_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -117.44934082031249
  - 32.59310597426537
  - 8
description: Port of Toner to TileMill2, building on Aaron Lidman's Toner-for-TileMill work
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1380431029885
name: Toner TM2
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v3"
styles: 
  - land.mss
  - roads.mss
  - boundaries.mss
  - palette.mss
template: ''
